// Code generated by protoc-gen-go.
// source: coordinate/structs.proto
// DO NOT EDIT!

/*
Package coordinate is a generated protocol buffer package.

It is generated from these files:
	coordinate/structs.proto

It has these top-level messages:
	Coordinate
*/
package coordinate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Coordinate struct {
	Vec        []float64 `protobuf:"fixed64,1,rep,packed,name=Vec,json=vec" json:"Vec,omitempty"`
	Error      float64   `protobuf:"fixed64,2,opt,name=Error,json=error" json:"Error,omitempty"`
	Adjustment float64   `protobuf:"fixed64,3,opt,name=Adjustment,json=adjustment" json:"Adjustment"`
	Height     float64   `protobuf:"fixed64,4,opt,name=Height,json=height" json:"Height,omitempty"`
}

func (m *Coordinate) Reset()                    { *m = Coordinate{} }
func (m *Coordinate) String() string            { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()               {}
func (*Coordinate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Coordinate) GetVec() []float64 {
	if m != nil {
		return m.Vec
	}
	return nil
}

func (m *Coordinate) GetError() float64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Coordinate) GetAdjustment() float64 {
	if m != nil {
		return m.Adjustment
	}
	return 0
}

func (m *Coordinate) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Coordinate)(nil), "coordinate.Coordinate")
}

func init() { proto.RegisterFile("coordinate/structs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xce, 0xcf, 0x2f,
	0x4a, 0xc9, 0xcc, 0x4b, 0x2c, 0x49, 0xd5, 0x2f, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x29, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0xc8, 0x28, 0xe5, 0x70, 0x71, 0x39, 0xc3, 0x79, 0x42,
	0x02, 0x5c, 0xcc, 0x61, 0xa9, 0xc9, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x8c, 0x41, 0xcc, 0x65, 0xa9,
	0xc9, 0x42, 0x22, 0x5c, 0xac, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x8c,
	0x41, 0xac, 0xa9, 0x20, 0x8e, 0x90, 0x1c, 0x17, 0x97, 0x63, 0x4a, 0x56, 0x69, 0x71, 0x49, 0x6e,
	0x6a, 0x5e, 0x89, 0x04, 0x33, 0x58, 0x8a, 0x2b, 0x11, 0x2e, 0x22, 0x24, 0xc6, 0xc5, 0xe6, 0x91,
	0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1, 0x02, 0x96, 0x63, 0xcb, 0x00, 0xf3, 0x92, 0xd8, 0xc0, 0x0e,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x76, 0xd9, 0x14, 0x9c, 0x00, 0x00, 0x00,
}
