// Code generated by protoc-gen-go.
// source: net.proto
// DO NOT EDIT!

/*
Package chord is a generated protocol buffer package.

It is generated from these files:
	net.proto

It has these top-level messages:
	Vnode
	Response
	VnodeList
	FindSuccReq
	StringParam
	VnodePair
*/
package chord

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import coordinate "github.com/hexablock/go-chord/coordinate"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vnode struct {
	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Meta []byte `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *Vnode) Reset()                    { *m = Vnode{} }
func (m *Vnode) String() string            { return proto.CompactTextString(m) }
func (*Vnode) ProtoMessage()               {}
func (*Vnode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vnode) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Vnode) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Vnode) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

// Generic response fields are available based on the type of response
type Response struct {
	Coordinate *coordinate.Coordinate `protobuf:"bytes,1,opt,name=Coordinate,json=coordinate" json:"Coordinate,omitempty"`
	Ok         bool                   `protobuf:"varint,2,opt,name=Ok,json=ok" json:"Ok,omitempty"`
	Vnode      *Vnode                 `protobuf:"bytes,3,opt,name=Vnode,json=vnode" json:"Vnode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetCoordinate() *coordinate.Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetVnode() *Vnode {
	if m != nil {
		return m.Vnode
	}
	return nil
}

type VnodeList struct {
	Vnodes []*Vnode `protobuf:"bytes,1,rep,name=vnodes" json:"vnodes,omitempty"`
}

func (m *VnodeList) Reset()                    { *m = VnodeList{} }
func (m *VnodeList) String() string            { return proto.CompactTextString(m) }
func (*VnodeList) ProtoMessage()               {}
func (*VnodeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VnodeList) GetVnodes() []*Vnode {
	if m != nil {
		return m.Vnodes
	}
	return nil
}

type FindSuccReq struct {
	VN    *Vnode `protobuf:"bytes,1,opt,name=VN,json=vN" json:"VN,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Key   []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *FindSuccReq) Reset()                    { *m = FindSuccReq{} }
func (m *FindSuccReq) String() string            { return proto.CompactTextString(m) }
func (*FindSuccReq) ProtoMessage()               {}
func (*FindSuccReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindSuccReq) GetVN() *Vnode {
	if m != nil {
		return m.VN
	}
	return nil
}

func (m *FindSuccReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FindSuccReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type StringParam struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *StringParam) Reset()                    { *m = StringParam{} }
func (m *StringParam) String() string            { return proto.CompactTextString(m) }
func (*StringParam) ProtoMessage()               {}
func (*StringParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StringParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type VnodePair struct {
	Target *Vnode `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Self   *Vnode `protobuf:"bytes,2,opt,name=self" json:"self,omitempty"`
}

func (m *VnodePair) Reset()                    { *m = VnodePair{} }
func (m *VnodePair) String() string            { return proto.CompactTextString(m) }
func (*VnodePair) ProtoMessage()               {}
func (*VnodePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VnodePair) GetTarget() *Vnode {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *VnodePair) GetSelf() *Vnode {
	if m != nil {
		return m.Self
	}
	return nil
}

func init() {
	proto.RegisterType((*Vnode)(nil), "chord.Vnode")
	proto.RegisterType((*Response)(nil), "chord.Response")
	proto.RegisterType((*VnodeList)(nil), "chord.VnodeList")
	proto.RegisterType((*FindSuccReq)(nil), "chord.FindSuccReq")
	proto.RegisterType((*StringParam)(nil), "chord.StringParam")
	proto.RegisterType((*VnodePair)(nil), "chord.VnodePair")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chord service

type ChordClient interface {
	ListVnodesServe(ctx context.Context, in *StringParam, opts ...grpc.CallOption) (*VnodeList, error)
	PingServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error)
	NotifyServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*VnodeList, error)
	GetPredecessorServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*Response, error)
	FindSuccessorsServe(ctx context.Context, in *FindSuccReq, opts ...grpc.CallOption) (*VnodeList, error)
	ClearPredecessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error)
	SkipSuccessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error)
}

type chordClient struct {
	cc *grpc.ClientConn
}

func NewChordClient(cc *grpc.ClientConn) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) ListVnodesServe(ctx context.Context, in *StringParam, opts ...grpc.CallOption) (*VnodeList, error) {
	out := new(VnodeList)
	err := grpc.Invoke(ctx, "/chord.chord/ListVnodesServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) PingServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/chord.chord/PingServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) NotifyServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*VnodeList, error) {
	out := new(VnodeList)
	err := grpc.Invoke(ctx, "/chord.chord/NotifyServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetPredecessorServe(ctx context.Context, in *Vnode, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/chord.chord/GetPredecessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessorsServe(ctx context.Context, in *FindSuccReq, opts ...grpc.CallOption) (*VnodeList, error) {
	out := new(VnodeList)
	err := grpc.Invoke(ctx, "/chord.chord/FindSuccessorsServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) ClearPredecessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/chord.chord/ClearPredecessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) SkipSuccessorServe(ctx context.Context, in *VnodePair, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/chord.chord/SkipSuccessorServe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chord service

type ChordServer interface {
	ListVnodesServe(context.Context, *StringParam) (*VnodeList, error)
	PingServe(context.Context, *VnodePair) (*Response, error)
	NotifyServe(context.Context, *VnodePair) (*VnodeList, error)
	GetPredecessorServe(context.Context, *Vnode) (*Response, error)
	FindSuccessorsServe(context.Context, *FindSuccReq) (*VnodeList, error)
	ClearPredecessorServe(context.Context, *VnodePair) (*Response, error)
	SkipSuccessorServe(context.Context, *VnodePair) (*Response, error)
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_ListVnodesServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ListVnodesServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/ListVnodesServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ListVnodesServe(ctx, req.(*StringParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_PingServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).PingServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/PingServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).PingServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_NotifyServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).NotifyServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/NotifyServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).NotifyServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetPredecessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vnode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/GetPredecessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessorServe(ctx, req.(*Vnode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessorsServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessorsServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/FindSuccessorsServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessorsServe(ctx, req.(*FindSuccReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_ClearPredecessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ClearPredecessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/ClearPredecessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ClearPredecessorServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_SkipSuccessorServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnodePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).SkipSuccessorServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.chord/SkipSuccessorServe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).SkipSuccessorServe(ctx, req.(*VnodePair))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chord.chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVnodesServe",
			Handler:    _Chord_ListVnodesServe_Handler,
		},
		{
			MethodName: "PingServe",
			Handler:    _Chord_PingServe_Handler,
		},
		{
			MethodName: "NotifyServe",
			Handler:    _Chord_NotifyServe_Handler,
		},
		{
			MethodName: "GetPredecessorServe",
			Handler:    _Chord_GetPredecessorServe_Handler,
		},
		{
			MethodName: "FindSuccessorsServe",
			Handler:    _Chord_FindSuccessorsServe_Handler,
		},
		{
			MethodName: "ClearPredecessorServe",
			Handler:    _Chord_ClearPredecessorServe_Handler,
		},
		{
			MethodName: "SkipSuccessorServe",
			Handler:    _Chord_SkipSuccessorServe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net.proto",
}

func init() { proto.RegisterFile("net.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6b, 0xdb, 0x30,
	0x14, 0xc6, 0x1b, 0xa7, 0x2e, 0xf5, 0x73, 0x59, 0x8b, 0xba, 0x8d, 0x10, 0x76, 0x08, 0xda, 0x0e,
	0xbd, 0xcc, 0xd9, 0x52, 0x08, 0x14, 0x36, 0x76, 0x28, 0x6c, 0x97, 0x91, 0x05, 0x19, 0x7a, 0x57,
	0xe4, 0x57, 0x47, 0x38, 0xb1, 0x32, 0x49, 0x36, 0xeb, 0x9f, 0xb2, 0xff, 0x76, 0x48, 0x76, 0x9b,
	0xa4, 0xf5, 0x20, 0x27, 0x4b, 0xef, 0xd3, 0xa7, 0xdf, 0xf7, 0xf4, 0x30, 0x44, 0x25, 0xda, 0x64,
	0xa3, 0x95, 0x55, 0x24, 0x14, 0x4b, 0xa5, 0xb3, 0xe1, 0x34, 0x97, 0x76, 0x59, 0x2d, 0x12, 0xa1,
	0xd6, 0xe3, 0x25, 0xfe, 0xe1, 0x8b, 0x95, 0x12, 0xc5, 0x38, 0x57, 0x1f, 0xbd, 0x3c, 0x16, 0x4a,
	0xe9, 0x4c, 0x96, 0xdc, 0xe2, 0xd8, 0x58, 0x5d, 0x09, 0x6b, 0x1a, 0x3b, 0xfd, 0x06, 0xe1, 0x5d,
	0xa9, 0x32, 0x24, 0xaf, 0x20, 0x90, 0xd9, 0xa0, 0x37, 0xea, 0x5d, 0x9d, 0xb1, 0x40, 0x66, 0x84,
	0xc0, 0xf1, 0x52, 0x19, 0x3b, 0x08, 0x46, 0xbd, 0xab, 0x88, 0xf9, 0xb5, 0xab, 0xad, 0xd1, 0xf2,
	0x41, 0xdf, 0x9f, 0xf2, 0x6b, 0x5a, 0xc3, 0x29, 0x43, 0xb3, 0x51, 0xa5, 0x41, 0x32, 0x05, 0xb8,
	0x7d, 0x02, 0xf9, 0xbb, 0xe2, 0xc9, 0xdb, 0x64, 0xcb, 0x4e, 0xb6, 0x2a, 0x83, 0x6d, 0xd9, 0xb1,
	0x7f, 0x15, 0x9e, 0x74, 0xca, 0x02, 0x55, 0x10, 0xda, 0x86, 0xf2, 0xa0, 0x78, 0x72, 0x96, 0xf8,
	0x26, 0x12, 0x5f, 0x63, 0x61, 0xed, 0x3e, 0xf4, 0x33, 0x44, 0x7e, 0xff, 0x53, 0x1a, 0x4b, 0x3e,
	0xc0, 0x89, 0xaf, 0x9a, 0x41, 0x6f, 0xd4, 0x7f, 0xe1, 0x68, 0x35, 0x9a, 0x42, 0xfc, 0x5d, 0x96,
	0x59, 0x5a, 0x09, 0xc1, 0xf0, 0x37, 0x79, 0x07, 0xc1, 0xdd, 0xac, 0x4d, 0xb9, 0x6f, 0x08, 0xea,
	0x19, 0x79, 0x0d, 0xa1, 0x50, 0x55, 0xd9, 0x3c, 0x40, 0xc8, 0x9a, 0x0d, 0xb9, 0x80, 0x7e, 0x81,
	0x0f, 0xed, 0x03, 0xb8, 0x25, 0x7d, 0x0f, 0x71, 0x6a, 0xb5, 0x2c, 0xf3, 0x39, 0xd7, 0x7c, 0xed,
	0x6c, 0x35, 0x5f, 0x55, 0x4d, 0xf7, 0x11, 0x6b, 0x36, 0x34, 0x6d, 0xc3, 0xce, 0xb9, 0xd4, 0x2e,
	0xac, 0xe5, 0x3a, 0x47, 0xdb, 0xc9, 0x6e, 0x35, 0x32, 0x82, 0x63, 0x83, 0xab, 0x7b, 0x8f, 0x7f,
	0x7e, 0xc6, 0x2b, 0x93, 0xbf, 0x7d, 0x68, 0x86, 0x4f, 0x6e, 0xe0, 0xdc, 0x3d, 0x83, 0x17, 0x4d,
	0x8a, 0xba, 0x46, 0x42, 0x5a, 0xc3, 0x4e, 0xb6, 0xe1, 0xc5, 0xee, 0x25, 0xce, 0x40, 0x8f, 0xc8,
	0x27, 0x88, 0xe6, 0xb2, 0xcc, 0x1b, 0xd3, 0xde, 0x01, 0x97, 0x75, 0x78, 0xde, 0x56, 0x1e, 0x47,
	0x4c, 0x8f, 0xc8, 0x35, 0xc4, 0x33, 0x65, 0xe5, 0xfd, 0xc3, 0xff, 0x3c, 0x5d, 0x98, 0x29, 0x5c,
	0xfe, 0x40, 0x3b, 0xd7, 0x98, 0xa1, 0x40, 0x63, 0x94, 0x6e, 0xcc, 0x7b, 0x6d, 0x75, 0xc1, 0xbe,
	0xc2, 0xe5, 0xe3, 0xc8, 0xbc, 0xed, 0x59, 0x77, 0x3b, 0xe3, 0xec, 0xc4, 0x7e, 0x81, 0x37, 0xb7,
	0x2b, 0xe4, 0xfa, 0x05, 0xf8, 0xa0, 0x4e, 0x6f, 0x80, 0xa4, 0x85, 0xdc, 0x3c, 0xc1, 0x0f, 0xb7,
	0x2e, 0x4e, 0xfc, 0xdf, 0x75, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x08, 0x52, 0xcf, 0xa9,
	0x03, 0x00, 0x00,
}
