// automatically generated by the FlatBuffers compiler, do not modify

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodeListErr struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodeListErr(buf []byte, offset flatbuffers.UOffsetT) *VnodeListErr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodeListErr{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodeListErr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodeListErr) Err() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VnodeListErr) Vnodes(obj *Vnode, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(Vnode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VnodeListErr) VnodesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VnodeListErrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func VnodeListErrAddErr(builder *flatbuffers.Builder, Err flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Err), 0)
}
func VnodeListErrAddVnodes(builder *flatbuffers.Builder, Vnodes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Vnodes), 0)
}
func VnodeListErrStartVnodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VnodeListErrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
