// automatically generated by the FlatBuffers compiler, do not modify

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodePair struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodePair(buf []byte, offset flatbuffers.UOffsetT) *VnodePair {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodePair{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodePair) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodePair) Target(obj *Vnode) *Vnode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Vnode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *VnodePair) Self(obj *Vnode) *Vnode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Vnode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func VnodePairStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func VnodePairAddTarget(builder *flatbuffers.Builder, Target flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Target), 0)
}
func VnodePairAddSelf(builder *flatbuffers.Builder, Self flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Self), 0)
}
func VnodePairEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
